name = "bili-random-worker"

main = "src/index.js"

compatibility_date = "2026-07-27"


# KV Namespace binding is configured manually:
#
# Cloudflare Dashboard
# → Workers & Pages
# → Your Worker
# → Settings
# → Bindings
#
[[kv_namespaces]]

binding = "VIDEOS"

id = "651504338ec64b7ebb4008d34220afc3"
