name = "bili-random-worker"

main = "src/index.js"

compatibility_date = "2026-07-27"


# KV 请在 Cloudflare Dashboard 手动绑定

# Workers
# ↓
# Settings
# ↓
# Bindings
# ↓
# KV Namespace


# Binding name:
# VIDEOS